[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_reexport = True
pretty = True

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-rank_bm25.*]
ignore_missing_imports = True
