/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Gibt HTTP 200 zurueck, solange der Prozess laeuft.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description Gibt alle eingereichten Use Cases als komprimierte Liste zurueck.
         *
         *     request: Request -- von slowapi benoetigt fuer Rate-Limit-Key-Extraktion.
         *     response: Response -- von slowapi benoetigt fuer Header-Injektion.
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 60 Requests/Minute pro API-Key.
         */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Case
         * @description Loescht einen Case kaskadiert (DSGVO Art. 17, ADR-0038).
         *
         *     request/response: von slowapi benoetigt (Rate-Limit-Key, Header-Injektion).
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 10/Minute -- schreibender/loeschender Zugriff, analog den
         *     LLM-Endpoints streng gehalten.
         *
         *     204 No Content bei Erfolg. CaseNotFoundError aus dem Service wird auf 404
         *     gemappt (HTTP-Exceptions in der Adapter-Schicht, ADR-0004).
         *
         *     Raises:
         *         HTTPException 404: case_id existiert nicht.
         */
        delete: operations["delete_case_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/sharpen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sharpen Case
         * @description Schaerft die Use-Case-Beschreibung eines bestehenden Cases via LLM.
         *
         *     request/response: von slowapi benoetigt (Rate-Limit-Key, Header-Injektion).
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 10/Minute -- enger als list_cases (60/min), da LLM-Endpoint
         *     (aect-security-checklist v2.1, Phase B: "LLM-Endpoints strenger").
         *
         *     Raises:
         *         HTTPException 404: case_id existiert nicht.
         */
        post: operations["sharpen_case_cases__case_id__sharpen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/propose-solution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Solution
         * @description Skizziert einen Loesungsansatz fuer einen bestehenden Case via LLM.
         *
         *     request/response: von slowapi benoetigt (Rate-Limit-Key, Header-Injektion).
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 10/Minute -- LLM-Endpoint, analog /sharpen
         *     (aect-security-checklist v2.1, Phase B: "LLM-Endpoints strenger").
         *
         *     Skeleton (Tag 36, Phase C): v1-Prompt nennt bewusst keine konkreten
         *     Zielplattformen -- Stack-Grounding via RAG folgt Phase D.
         *
         *     Raises:
         *         HTTPException 404: case_id existiert nicht.
         */
        post: operations["propose_solution_cases__case_id__propose_solution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Report
         * @description Erstellt den zweischichtigen Report fuer einen bestehenden Case.
         *
         *     request/response: von slowapi benoetigt (Rate-Limit-Key, Header-Injektion).
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 30/Minute -- kein LLM-Call (Regel-Schicht), aber Request-Body
         *     -- zwischen list_cases (60/min, lesend) und /sharpen (10/min, LLM).
         *
         *     body: optional. Ohne Body (oder mit None-Feldern) werden die
         *     persistierten Werte aus /sharpen bzw. /propose-solution verwendet
         *     (Tag 42, ADR-0012). Ein gesetztes Feld ueberschreibt den persistierten
         *     Wert fuer diese Antwort, ohne ihn zu aendern. compliance_hint_text/
         *     compliance_citations kommen immer aus der Persistenz (ADR-0026), kein
         *     Override.
         *
         *     Raises:
         *         HTTPException 404: case_id existiert nicht.
         */
        post: operations["get_report_cases__case_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/compliance-hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compliance Hints
         * @description Erstellt RAG-gegruendete Compliance-Hinweise fuer einen bestehenden Case.
         *
         *     request/response: von slowapi benoetigt (Rate-Limit-Key, Header-Injektion).
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 10/Minute -- LLM-Endpoint, analog /sharpen und
         *     /propose-solution (aect-security-checklist v2.1, Phase B: "LLM-Endpoints
         *     strenger").
         *
         *     Raises:
         *         HTTPException 404: case_id existiert nicht.
         */
        post: operations["compliance_hints_cases__case_id__compliance_hints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Use Case
         * @description Reicht einen Use Case ein und gibt das vollstaendige Triage-Ergebnis zurueck.
         *
         *     request: Request -- von slowapi benoetigt fuer Rate-Limit-Key-Extraktion.
         *     Auth: X-API-Key-Header (require_api_key).
         *     Rate Limit: 30 Requests/Minute pro API-Key.
         *     Validation: extra='forbid' auf UseCaseInput -- unbekannte Felder -> 422.
         *
         *     Idempotency: siehe Modul-Docstring. Bei Replay wird response.status_code
         *     auf 200 gesetzt und der Header 'Idempotent-Replay: true' ergaenzt.
         */
        post: operations["submit_use_case_triage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdoptionType
         * @description Verbindlichkeit der Nutzung — beeinflusst den Nutzungsfaktor im ROI-Modell.
         * @enum {string}
         */
        AdoptionType: "mandatory" | "voluntary";
        /**
         * BusinessSummaryResponse
         * @description Entscheider-Schicht des Reports.
         *
         *     compliance_hint_text/compliance_citations (ADR-0026): aus dem
         *     persistierten compliance_hints_json gelesen, kein Override moeglich
         *     (siehe ReportRequest-Docstring).
         */
        BusinessSummaryResponse: {
            /** Title */
            title: string;
            /** Zone */
            zone: string | null;
            /** Is Actionable */
            is_actionable: boolean;
            /** Recommendation */
            recommendation: string;
            /** Expected Benefit Eur */
            expected_benefit_eur: number | null;
            /** Summary Text */
            summary_text: string;
            /** Sharpened Text */
            sharpened_text: string | null;
            /** Compliance Hint Text */
            compliance_hint_text: string | null;
            /** Compliance Citations */
            compliance_citations: components["schemas"]["ComplianceCitationResponse"][];
        };
        /**
         * CaseSummary
         * @description Komprimiertes Case-Ergebnis fuer die Listansicht.
         */
        CaseSummary: {
            /** Id */
            id: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Title */
            title: string;
        };
        /**
         * ComplianceCitationResponse
         * @description Eine einzelne Quellenangabe -- Compliance-Hinweis-Endpoint UND
         *     /report (ADR-0026). Vor BusinessSummaryResponse definiert, damit
         *     letztere sie referenzieren kann.
         */
        ComplianceCitationResponse: {
            /** Number */
            number: number;
            /** Source Id */
            source_id: string;
            /** Citation */
            citation: string;
            /** Url */
            url: string | null;
        };
        /**
         * ComplianceHintsResponse
         * @description RAG-gegruendete Compliance-Hinweise (Master-Plan v3.1 Phase D, ADR-0024).
         *
         *     hint_text: None wenn das Retrieval keine Treffer lieferte (Graceful
         *     Degradation, kein ungegruendeter Hinweis -- kein LLM-Call in diesem Fall).
         *     citations: leer wenn hint_text None ist, sonst 1-basiert nummeriert,
         *     identisch zu den [N]-Referenzen in hint_text.
         */
        ComplianceHintsResponse: {
            /** Case Id */
            case_id: string;
            /** Hint Text */
            hint_text: string | null;
            /** Citations */
            citations: components["schemas"]["ComplianceCitationResponse"][];
            /** Prompt Version */
            prompt_version: string;
        };
        /** CompositeScoreResponse */
        CompositeScoreResponse: {
            /** Complexity Score */
            complexity_score: number;
            /** Cost Score */
            cost_score: number;
            /** Data Protection Score */
            data_protection_score: number;
            /** Total */
            total: number;
            /** Effort Label */
            effort_label: string;
        };
        /**
         * DataClassification
         * @description Datenschutz-Einstufung der verarbeiteten Daten.
         *
         *     Beeinflusst den Datenschutz-Anteil im Composite-Aufwand-Score (aufsteigend).
         *     Score-Mapping: NO_PERSONAL_DATA=0, PSEUDONYMOUS=1, PERSONAL=1, SENSITIVE_PERSONAL=2.
         *     Mapping liegt in config, nicht hier.
         * @enum {string}
         */
        DataClassification: "no_personal_data" | "pseudonymous" | "personal" | "sensitive_personal";
        /**
         * EmployeeCategory
         * @description Grobe Seniorität der betroffenen Mitarbeiter.
         *
         *     Konkretes Stundensatz-Mapping (je Land x Stufe) liegt in config/roi_config.yaml.
         *     Dieses Enum ist der IP-saubere Anker — keine Firmenzahlen im Code.
         * @enum {string}
         */
        EmployeeCategory: "junior" | "professional" | "senior" | "mixed";
        /**
         * EvidenceLevel
         * @description Qualität der Zeitersparnis-Schätzung.
         *
         *     Beeinflusst den Evidenzfaktor im ROI-Modell (aufsteigend nach Verlässlichkeit).
         *     Konkretes Faktor-Mapping (z. B. 0.5 / 0.75 / 0.95) liegt in config/roi_config.yaml.
         * @enum {string}
         */
        EvidenceLevel: "pure_estimate" | "similar_project" | "tested_piloted";
        /** FeasibilityResponse */
        FeasibilityResponse: {
            /** Is Feasible */
            is_feasible: boolean;
            /** Flags */
            flags: string[];
            /** Recommendation */
            recommendation: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response-Schema fuer GET /health.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ImplementationApproach
         * @description Geplante Umsetzungsstrategie.
         * @enum {string}
         */
        ImplementationApproach: "standard_product" | "custom_build" | "vendor_solution";
        /** ROIResponse */
        ROIResponse: {
            /** Theoretical Potential Eur */
            theoretical_potential_eur: number;
            /** Expected Benefit Eur */
            expected_benefit_eur: number;
            /** Net Expected Benefit Eur */
            net_expected_benefit_eur: number;
            /** Hours Per Year */
            hours_per_year: number;
            /** Usage Factor */
            usage_factor: number;
            /** Evidence Factor */
            evidence_factor: number;
            /** License Cost Annual Eur */
            license_cost_annual_eur: number;
            /** Passes Prefilter */
            passes_prefilter: boolean;
            /** Prefilter Fail Reason */
            prefilter_fail_reason: string | null;
        };
        /**
         * ReportRequest
         * @description Optionale LLM-Narrative fuer den Report -- Override der Persistenz.
         *
         *     Tag 42 (ADR-0012): generate_report() liest sharpened_text/proposal_text
         *     standardmaessig aus dem persistierten SubmittedCase (gefuellt durch
         *     /sharpen bzw. /propose-solution). Felder hier ueberschreiben den
         *     persistierten Wert, z. B. fuer eine Vorschau ohne erneuten Persist.
         *     extra="forbid" + max_length: aect-security-checklist v2.1 Phase A
         *     (Token-Flooding-Schutz, LLM10) -- gilt als generelle Eingabe-Disziplin
         *     auch fuer Felder ohne direkten LLM-Call.
         *
         *     Kein Override-Feld fuer Compliance-Hinweise (ADR-0026) -- siehe
         *     application/service.py generate_report()-Docstring.
         */
        ReportRequest: {
            /** Sharpened Text */
            sharpened_text?: string | null;
            /** Proposal Text */
            proposal_text?: string | null;
        };
        /**
         * ReportResponse
         * @description Zweischichtiger Report -- striktes JSON (Projekt-Anforderung).
         */
        ReportResponse: {
            /** Case Id */
            case_id: string;
            business_summary: components["schemas"]["BusinessSummaryResponse"];
            technical_detail: components["schemas"]["TechnicalDetailResponse"];
        };
        /** RoutingResponse */
        RoutingResponse: {
            /** Recommendation */
            recommendation: string;
            /** Confidence */
            confidence: string;
            /** Automation Signals */
            automation_signals: string[];
            /** Ai Signals */
            ai_signals: string[];
            /** Risk Flags */
            risk_flags: string[];
            /** Requires Human Review */
            requires_human_review: boolean;
        };
        /**
         * SharpenedCaseResponse
         * @description Original + geschaerfte Version eines Use Cases (ADR-0013 Teil 2).
         *
         *     Erfolg: sharpened_title/current_state/desired_state gesetzt,
         *     improvement_suggestions hat 1-10 Eintraege, raw_text ist None.
         *     Graceful Degradation: die drei sharpened_*-Felder sind None,
         *     improvement_suggestions ist leer, raw_text enthaelt die rohe
         *     LLM-Antwort (aect-security-checklist v2.1: LLM-Output als untrusted,
         *     kein Crash bei Format-Verstoss).
         */
        SharpenedCaseResponse: {
            /** Case Id */
            case_id: string;
            /** Original Title */
            original_title: string;
            /** Original Current State */
            original_current_state: string;
            /** Original Desired State */
            original_desired_state: string;
            /** Sharpened Title */
            sharpened_title: string | null;
            /** Sharpened Current State */
            sharpened_current_state: string | null;
            /** Sharpened Desired State */
            sharpened_desired_state: string | null;
            /** Improvement Suggestions */
            improvement_suggestions: string[];
            /** Raw Text */
            raw_text: string | null;
            /** Prompt Version */
            prompt_version: string;
        };
        /**
         * SimilarityWarning
         * @description Hinweis auf einen aehnlichen, bereits eingereichten Case (L-3, ADR-0039).
         *
         *     Wird bei Intake (POST /triage) erzeugt, wenn die Embedding-Cosinus-
         *     Aehnlichkeit des neuen Cases zu einem bestehenden Case eine Schwelle
         *     ueberschreitet. Rein additiv -- veraendert die Triage-Entscheidung nicht.
         *
         *     similarity_score: Cosinus-Aehnlichkeit [0.0, 1.0] zum aehnlichsten Case.
         *     suggest_combine: True ab der hoeheren Schwelle (>= 0.90) -- "wahrscheinlich
         *     derselbe Use Case, zusammenlegen?". False im Awareness-Bereich
         *     ([0.75, 0.90)) -- "es gibt etwas Aehnliches, bitte pruefen".
         */
        SimilarityWarning: {
            /** Similar Case Id */
            similar_case_id: string;
            /** Similar Case Title */
            similar_case_title: string;
            /** Similarity Score */
            similarity_score: number;
            /** Suggest Combine */
            suggest_combine: boolean;
        };
        /**
         * SolutionProposalResponse
         * @description Stack-passender Loesungsvorschlag fuer einen Use Case (Skeleton).
         */
        SolutionProposalResponse: {
            /** Case Id */
            case_id: string;
            /** Proposal Text */
            proposal_text: string;
            /** Prompt Version */
            prompt_version: string;
        };
        /**
         * TechnicalDetailResponse
         * @description Reviewer-Schicht des Reports.
         */
        TechnicalDetailResponse: {
            /** Passed Vorfilter */
            passed_vorfilter: boolean;
            /** Vorfilter Failed Criteria */
            vorfilter_failed_criteria: string[];
            /** Composite Total */
            composite_total: number | null;
            /** Composite Effort Label */
            composite_effort_label: string | null;
            /** Feasibility Flags */
            feasibility_flags: string[];
            /** Feasibility Recommendation */
            feasibility_recommendation: string | null;
            /** Automation Signals */
            automation_signals: string[];
            /** Ai Signals */
            ai_signals: string[];
            /** Risk Flags */
            risk_flags: string[];
            /** Requires Human Review */
            requires_human_review: boolean;
            /** Roi Theoretical Potential Eur */
            roi_theoretical_potential_eur: number | null;
            /** Roi Net Expected Benefit Eur */
            roi_net_expected_benefit_eur: number | null;
            /** Proposal Text */
            proposal_text: string | null;
        };
        /**
         * TriageResponse
         * @description Vollstaendiges Triage-Ergebnis fuer einen eingereichten Use Case.
         *
         *     roi, composite und zone sind None wenn passed_vorfilter False ist.
         */
        TriageResponse: {
            /** Id */
            id: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Title */
            title: string;
            /** Passed Vorfilter */
            passed_vorfilter: boolean;
            /** Is Actionable */
            is_actionable: boolean;
            vorfilter: components["schemas"]["VorfilterResponse"];
            routing: components["schemas"]["RoutingResponse"];
            feasibility: components["schemas"]["FeasibilityResponse"];
            roi: components["schemas"]["ROIResponse"] | null;
            composite: components["schemas"]["CompositeScoreResponse"] | null;
            zone: components["schemas"]["ZoneResponse"] | null;
            similarity_warning?: components["schemas"]["SimilarityWarning"] | null;
        };
        /**
         * UseCaseInput
         * @description Eingabe-Schema für einen AI-Use-Case-Antrag.
         *
         *     Entspricht den Feldern des v5-Bewertungsmodells:
         *     Stammdaten / Ist-Soll / Mengen / Zeit / Evidenz / Verbindlichkeit /
         *     Kosten / Datenschutz / Handlungsdruck.
         *
         *     Alle Freitextfelder: min_length + max_length (Substanz + Token-Budget).
         *     Alle Enum-Felder: StrEnum — parst direkt aus JSON-Strings.
         *     Die Rule Engine (Phase A) liest ausschließlich dieses Objekt.
         */
        UseCaseInput: {
            /**
             * Title
             * @description Kurzer, sprechender Name des Use Case
             */
            title: string;
            /**
             * Submitter
             * @description Name der einreichenden Person
             */
            submitter: string;
            /**
             * Department
             * @description Abteilung / Organisationseinheit
             */
            department: string;
            /**
             * Current State
             * @description Beschreibung des aktuellen Prozesses (Ist-Zustand)
             */
            current_state: string;
            /**
             * Desired State
             * @description Beschreibung des gewünschten Zustands nach AI-Einsatz
             */
            desired_state: string;
            /**
             * Example Process
             * @description Konkretes Beispiel eines einzelnen Vorgangs (nicht Gesamtvolumen)
             */
            example_process: string;
            /**
             * Time Savings Hours Per Case
             * @description Geschätzte Zeitersparnis pro Vorgang in Stunden (max = 8 h)
             */
            time_savings_hours_per_case: number;
            /**
             * Frequency Per Year
             * @description Anzahl Vorgänge pro Jahr
             */
            frequency_per_year: number;
            /**
             * Affected Employees Count
             * @description Anzahl Mitarbeiter, die diesen Prozess heute manuell durchführen
             */
            affected_employees_count: number;
            /** @description Grobe Seniorität der betroffenen Mitarbeiter (→ Stundensatz aus Config) */
            employee_category: components["schemas"]["EmployeeCategory"];
            /**
             * @description Qualität der Grundlage für die Zeitersparnis-Schätzung
             * @default pure_estimate
             */
            evidence_level: components["schemas"]["EvidenceLevel"];
            /** @description Pflicht- oder Freiwillignutzung (beeinflusst Nutzungsfaktor) */
            adoption_type: components["schemas"]["AdoptionType"];
            /** @description Geplante Umsetzungsstrategie */
            implementation_approach: components["schemas"]["ImplementationApproach"];
            /**
             * Estimated License Cost Eur
             * @description Geschätzte Lizenzkosten p.a. in EUR (0 = open-source oder intern gebaut)
             * @default 0
             */
            estimated_license_cost_eur: number;
            /**
             * Implementation Complexity
             * @description Technische Komplexität: 1 = trivial, 3 = mittel, 5 = sehr hoch
             */
            implementation_complexity: number;
            /**
             * Contains Pii
             * @description Werden personenbezogene Daten verarbeitet? (Schnellcheck)
             * @default false
             */
            contains_pii: boolean;
            /** @description Datenschutz-Einstufung der verarbeiteten Daten. SENSITIVE_PERSONAL → Datenschutz-Score 2 im Composite-Aufwand-Score. */
            data_classification: components["schemas"]["DataClassification"];
            /**
             * Regulatory Pressure
             * @description Regulatorischer Druck (Compliance-Anforderung, Audit-Finding)?
             * @default false
             */
            regulatory_pressure: boolean;
            /**
             * Competitive Pressure
             * @description Wettbewerbsdruck (Branche setzt AI bereits ein)?
             * @default false
             */
            competitive_pressure: boolean;
            /**
             * Strategic Priority
             * @description Explizit strategische Priorität von Vorstand oder Management?
             * @default false
             */
            strategic_priority: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VorfilterResponse */
        VorfilterResponse: {
            /** Passes */
            passes: boolean;
            /** Failed Criteria */
            failed_criteria: string[];
            /** Details */
            details: {
                [key: string]: boolean;
            };
        };
        /** ZoneResponse */
        ZoneResponse: {
            /** Base Zone */
            base_zone: string;
            /** Final Zone */
            final_zone: string;
            /** Handlungsdruck Elevated */
            handlungsdruck_elevated: boolean;
            /** Reason */
            reason: string;
            /** Confidence Score */
            confidence_score: number;
            /** Confidence Label */
            confidence_label: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"][];
                };
            };
        };
    };
    delete_case_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sharpen_case_cases__case_id__sharpen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharpenedCaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_solution_cases__case_id__propose_solution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_cases__case_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReportRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compliance_hints_cases__case_id__compliance_hints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceHintsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_use_case_triage_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UseCaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
